# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(790, 0, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lbl_img = QtWidgets.QLabel(self.centralwidget)
        self.lbl_img.setGeometry(QtCore.QRect(10, 100, 640, 431))
        self.lbl_img.setStyleSheet("background-color:#fff")
        self.lbl_img.setText("")
        self.lbl_img.setObjectName("lbl_img")
        self.lbl_manual_cam = QtWidgets.QLabel(self.centralwidget)
        self.lbl_manual_cam.setGeometry(QtCore.QRect(70, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_manual_cam.setFont(font)
        self.lbl_manual_cam.setStyleSheet("background-color:#fff;\n"
"border-radius:16px;\n"
"")
        self.lbl_manual_cam.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_manual_cam.setObjectName("lbl_manual_cam")
        self.table_result = QtWidgets.QTableWidget(self.centralwidget)
        self.table_result.setGeometry(QtCore.QRect(660, 100, 421, 431))
        self.table_result.setStyleSheet("background-color:rgb(251, 255, 205)")
        self.table_result.setRowCount(10)
        self.table_result.setColumnCount(3)
        self.table_result.setObjectName("table_result")
        self.lbl_manual_cam_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_manual_cam_2.setGeometry(QtCore.QRect(680, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_manual_cam_2.setFont(font)
        self.lbl_manual_cam_2.setStyleSheet("background-color:#fff;\n"
"border-radius:16px;\n"
"")
        self.lbl_manual_cam_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_manual_cam_2.setObjectName("lbl_manual_cam_2")
        self.btnLogout = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogout.setGeometry(QtCore.QRect(940, 550, 93, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnLogout.setFont(font)
        self.btnLogout.setObjectName("btnLogout")
        self.btnCapture = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapture.setGeometry(QtCore.QRect(40, 540, 93, 28))
        self.btnCapture.setObjectName("btnCapture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_manual_cam.setText(_translate("MainWindow", "Camera"))
        self.lbl_manual_cam_2.setText(_translate("MainWindow", "Result"))
        self.btnLogout.setText(_translate("MainWindow", "Logout"))
        self.btnCapture.setText(_translate("MainWindow", "Captures"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
